-- Room comments + auth profiles
-- Run this in the Supabase SQL editor (after schema.sql). Safe to re-run.
--
-- Also requires enabling the Google and/or Apple providers under
-- Authentication > Providers in the Supabase dashboard.

-- ---------------------------------------------------------------------------
-- profiles
--   Public, RLS-safe mirror of auth.users (which is not readable by clients)
--   so comments can display a name. New users get an anonymous handle
--   ("Shark #0421") generated by a trigger — real names and avatars from the
--   OAuth provider are deliberately never shown; they're unmoderated user
--   content. Users may change their handle (column-level grant below).
-- ---------------------------------------------------------------------------
create or replace function generate_handle()
returns text
language sql volatile
as $$
  select 'Shark #' || lpad(floor(random() * 10000)::text, 4, '0')
$$;

create table if not exists profiles (
    id           uuid primary key references auth.users (id) on delete cascade,
    display_name text not null default 'Student',
    created_at   timestamptz not null default now()
);

-- In case an earlier version of this script (which had avatars) already ran
alter table profiles drop column if exists avatar_url;

-- Keep custom handles sane: trimmed, 3-24 chars, no URLs/symbols beyond the
-- few needed for the generated format. (Profanity isn't filtered — moderate
-- via the Supabase dashboard if needed.)
alter table profiles drop constraint if exists profiles_display_name_check;
alter table profiles add constraint profiles_display_name_check check (
    display_name = btrim(display_name)
    and char_length(display_name) between 3 and 24
    and display_name ~ '^[A-Za-z0-9 #_.\-]+$'
);

create or replace function handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, display_name)
  values (new.id, generate_handle())
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
  after insert on auth.users
  for each row execute function handle_new_user();

-- Backfill in case any users signed up before this trigger existed.
insert into profiles (id, display_name)
select u.id, generate_handle()
from auth.users u
on conflict (id) do nothing;

-- ---------------------------------------------------------------------------
-- comments
--   user_id references profiles (not auth.users) so PostgREST can embed the
--   author's profile in a single query. classrooms rows are upserted (never
--   deleted) by the scraper, so the FK is stable across scrape runs.
-- ---------------------------------------------------------------------------
create table if not exists comments (
    id           uuid primary key default gen_random_uuid(),
    classroom_id uuid not null references classrooms (id) on delete cascade,
    user_id      uuid not null references profiles (id) on delete cascade,
    content      text not null check (char_length(btrim(content)) between 1 and 500),
    created_at   timestamptz not null default now()
);

create index if not exists idx_comments_classroom
    on comments (classroom_id, created_at desc);
-- Supports the rate-limit trigger's per-user lookups
create index if not exists idx_comments_user_created
    on comments (user_id, created_at desc);

-- ---------------------------------------------------------------------------
-- Spam guard: enforced in the database so it can't be bypassed by calling
-- the API directly. The raised messages are shown to the user by the app.
--   - 30s cooldown between comments
--   - 20 comments per user per day
--   - no reposting identical text within 10 minutes
-- security definer so the counts see all rows regardless of RLS.
-- ---------------------------------------------------------------------------
create or replace function check_comment_rate_limit()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  if exists (
    select 1 from comments
    where user_id = new.user_id
      and created_at > now() - interval '30 seconds'
  ) then
    raise exception 'You''re commenting too fast. Try again in a moment.';
  end if;

  if (
    select count(*) from comments
    where user_id = new.user_id
      and created_at > now() - interval '1 day'
  ) >= 20 then
    raise exception 'Daily comment limit reached. Try again tomorrow.';
  end if;

  if exists (
    select 1 from comments
    where user_id = new.user_id
      and content = new.content
      and created_at > now() - interval '10 minutes'
  ) then
    raise exception 'Looks like a duplicate comment.';
  end if;

  return new;
end;
$$;

drop trigger if exists comments_rate_limit on comments;
create trigger comments_rate_limit
  before insert on comments
  for each row execute function check_comment_rate_limit();

-- ---------------------------------------------------------------------------
-- Row Level Security: anyone can read; only signed-in users can post, and
-- only as themselves; users can delete only their own comments and can
-- update only their own display_name (column-level grant — other profile
-- columns stay read-only).
-- ---------------------------------------------------------------------------
alter table profiles enable row level security;
alter table comments enable row level security;

drop policy if exists "public read" on profiles;
create policy "public read" on profiles
    for select to anon, authenticated using (true);
drop policy if exists "update own" on profiles;
create policy "update own" on profiles
    for update to authenticated using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "public read" on comments;
create policy "public read" on comments
    for select to anon, authenticated using (true);
drop policy if exists "insert own" on comments;
create policy "insert own" on comments
    for insert to authenticated with check (auth.uid() = user_id);
drop policy if exists "delete own" on comments;
create policy "delete own" on comments
    for delete to authenticated using (auth.uid() = user_id);

revoke update on profiles from anon, authenticated;
grant update (display_name) on profiles to authenticated;
